package io.github.insideranh.stellarprotect.entities;

public enum DataEntityType {

    AI,
    CAN_PICKUP_ITEMS,
    COLLIDABLE,
    REMAINING_AIR,

    // ALL
    MAX_HEALTH,
    HEALTH,

    // DOG, CAT
    COLLAR_COLOR,

    // CAT
    CAT_TYPE,
    CAT_VARIANT,

    HORSE_COLOR,
    HORSE_STYLE,
    JUMP_STRENGTH,
    HORSE_ARMOR,

    LLAMA_COLOR,
    LLAMA_STRENGTH,
    LLAMA_CARPET,

    PARROT_VARIANT,

    RABBIT_TYPE,

    SHEEP_COLOR,
    SHEEP_SHEARED,

    PIG_SADDLED,

    HAS_SADDLE,

    CREEPER_POWERED,
    CREEPER_MAX_FUSE,
    CREEPER_EXPLOSION_RADIUS,

    PANDA_MAIN_GENE,
    PANDA_HIDDEN_GENE,

    PIGLIN_IMMUNE_TO_ZOMBIFICATION,
    PIGLIN_BABY,

    HOGLIN_IMMUNE_TO_ZOMBIFICATION,
    HOGLIN_HUNTING_COOLDOWN,

    STRIDER_SADDLED,

    GOAT_SCREAMING,

    FROG_VARIANT,

    ALLAY_CAN_DUPLICATE,
    ALLAY_DUPLICATION_COOLDOWN,

    WARDEN_ANGER,

    SNIFFER_STATE,

    CAMEL_DASHING,

    ARMADILLO_STATE,

    ZOMBIE_BABY,
    ZOMBIE_CONVERTING_DROWNED,

    IRON_GOLEM_PLAYER_CREATED,

    SNOWMAN_DERP,

    // DOG
    DOG_VARIANT,
    DOG_ANGRY,
    DOG_WET,

    ANGRY,
    WOLF_VARIANT,

    // VILLAGER
    VILLAGER_PROFESSION,
    VILLAGER_TYPE,
    VILLAGER_REPUTATION,
    VILLAGER_LEVEL,
    VILLAGER_EXPERIENCE,
    VILLAGER_TRADES,

    ENTITY_TYPE,
    CUSTOM_NAME,
    CUSTOM_NAME_VISIBLE,
    SILENT,
    INVISIBLE,
    GRAVITY,
    FIRE_TICKS,
    POTION_EFFECTS,

    GLOWING,
    LEASH_HOLDER_ID,

    INVULNERABLE,
    TAMED,
    AGE,

    ARMOR_STAND_ARMS,
    ARMOR_STAND_BASE_PLATE,
    ARMOR_STAND_MARKER,
    ARMOR_STAND_SMALL,
    ARMOR_STAND_VISIBLE,
    ARMOR_STAND_HEAD_POSE,
    ARMOR_STAND_BODY_POSE,
    ARMOR_STAND_LEFT_ARM_POSE,
    ARMOR_STAND_RIGHT_ARM_POSE,
    ARMOR_STAND_LEFT_LEG_POSE,
    ARMOR_STAND_RIGHT_LEG_POSE,

    ENDERMAN_CARRIED_BLOCK,

    ITEM_FRAME_ITEM,
    ITEM_FRAME_ROTATION,
    ITEM_FRAME_VISIBLE,
    ITEM_FRAME_FIXED,
    ITEM_FRAME_GLOWING,

    SHULKER_COLOR,

    BABY,
    ADULT,
    AGE_LOCK,

    OWNER_UUID,

    AWARE,
    TARGET_UUID,

    CONVERTING,
    CONVERSION_TIME,

    FOX_TYPE,
    FOX_CROUCHING,
    FOX_SLEEPING,

    BEE_HAS_NECTAR,
    BEE_HAS_STUNG,
    BEE_ANGER,

    AXOLOTL_VARIANT,

    TROPICAL_FISH_PATTERN,
    TROPICAL_FISH_BODY_COLOR,
    TROPICAL_FISH_PATTERN_COLOR,

    PHANTOM_SIZE,

    SLIME_SIZE,

}